### ISSUE TITLE
Doesn't work on mac

### ISSUE THREAD

**Issue by unitoftime** [unitoftime/glitch#3]
2022/06/16 02:51:30 failed diffues
panic: loadShader: ERROR: 0:1: '' :  version '300' is not supported
ERROR: 0:1: '' : syntax error: #version
ERROR: 0:2: '' :  #version required and missing.
ERROR: 0:3: '0' : syntax error: integers in layouts require GLSL 140 or later

goroutine 19 [running]:
main.runGame()
        /Users/____/Documents/GitHub/raylib-game-1/main.go:27 +0xe4c
github.com/faiface/mainthread.Run.func1()
        /Users/_____/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x26
created by github.com/faiface/mainthread.Run
        /Users/_____/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xb8
exit status 2

**Comment by unitoftime** [comment]
Todo - buy a mac

**Comment by nathany** [comment]
It was a small change to get `go run examples/simple/main.go` running on macOS 15.5, but it may be a bigger change to support both macOS and WebGL 2 at the same time.

![Image](https://github.com/user-attachments/assets/50f60cc2-b47e-4016-aa13-7c8d66b157d6)

Without #13 ANGLE, macOS doesn't support OpenGL ES. It also doesn't appear to have shader language 300 listed in GLview.

![Image](https://github.com/user-attachments/assets/ada43107-f6fc-444c-8742-f0cd8f83555f)

To get it to run, I tried using shader version 330 without the ES suffix.

![Image](https://github.com/user-attachments/assets/2930f485-a93b-4bac-8e19-22081a534fd9)

**Comment by unitoftime** [comment]
Yeah. Good ideas. At this point I'm fine with leaving it as is, I don't really have a macOS usecase for Mythfall. But if someone else wants it for their use case, they can either manually set their shaders or submit a patch.
